### ISSUE TITLE
Optimize function Execute

### ISSUE THREAD

**Issue by beruangcoklat** [raymondhartoyo/gorutin#1]
I think it would be better to use a single output channel rather than an array of output channels. It would be more efficient to check if we already get all of the outputs.

Something like this:
```
go func() {
	waitGroup.Wait()
	close(outputChannel)
}()

outputs := []TypeOut{}
for o := range outputChannel {
	outputs = append(outputs, o)
}
```
I would be willing to file a PR if that is acceptable.

**Comment by raymondhartoyo** [comment]
👍 You're right, that's true. Before, I was actually thinking to use the outputChannel as an indicator if a goroutine is done or not because I was thinking about context cancellation or timeouts, etc. But after hearing some feedback from others and reviewing the approach, it seems the inputChannel and outputChannel doesn't have to be per goroutines, which means 1 channel is enough for input and 1 for the output.

I am currently working on this to refactor the inputChannel as well, will create a PR soon and release it 😃

**Comment by raymondhartoyo** [comment]
updated on v0.1.2

closing this issue, feel free to reopen if you still have other feedback
